import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const ID = 'a89f7a00-092f-45c1-a908-b9ba465a27f5';
const antes = await sb.from('servicios').select('id, nombre, precio').eq('id', ID).single();
console.log('antes:', JSON.stringify(antes.data), antes.error?.message || '');
const up = await sb.from('servicios').update({ precio: 297 }).eq('id', ID).select('id, nombre, precio').single();
console.log('despues:', JSON.stringify(up.data), up.error?.message || '');
const ver = await sb.from('servicios').select('nombre, slug, precio').eq('slug', 'impuestos/declaracion-anual-llc').single();
console.log('verificacion:', JSON.stringify(ver.data));